#########################################
# firebase にgithub actions からデプロイする
# 以下の環境変数を設定する
# FIREBASE_TOKEN_PROD
# FIREBASE_PROJECT
# トークンは、firebase login:ciで取得する
#########################################
name: CD

on: 
  push:
    branches:
      - main
env:
  VITE_GEMINI_PRO_API_KEY: ${{ secrets.VITE_GEMINI_PRO_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools
      
      - name: Install dependencies
        run: |
          npm install

      - name: Build React
        run: |
          npm run build

      - name: Deploy
        env:
          FIREBASE_TOKEN_PROD: ${{ secrets.FIREBASE_TOKEN_PROD }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        run: |
          firebase deploy  --only hosting --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN_PROD